server:
  port: 9999

spring:
  datasource:
    username: root
    password: 194466
    url: jdbc:mysql:///demo_db
  redis:
    port: 6379
    host: localhost

logging:
  level:
    org.ytq: debug

# 逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: org.ytq.*.entity
